--- 
servers:
  host1:
    adapters:
      - type: servers
        switch_ports: [ Ethernet6, Ethernet7, Ethernet6, Ethernet7 ]
        switches: [ leaf1, leaf1, leaf2, leaf2]
        vlans: 10
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          mode: active
  host2:
    adapters:
      - type: servers
        switch_ports: [ Ethernet6, Ethernet7, Ethernet6, Ethernet7 ]
        switches: [ leaf3, leaf3, leaf4, leaf4]
        vlans: 20
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          mode: active    