---
tenants:
  ACME:
    mac_vrf_vni_base: 10000
    vrfs:
      Red:
        vrf_vni: 10
        svis:
          10: 
            name: DMZ
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          20: 
            name: Internal
            enabled: true
            ip_address_virtual: 10.1.20.1/24
        l3_interfaces:
          - interfaces: [Ethernet7]
            ip_addresses: [10.1.5.0/31]
            nodes: [leaf4]
            enabled: True 
        bgp_peers:
          - ip_address: 10.1.5.1
            remote_as: 1
            nodes: [leaf4]