---
tenants:
  ACME:
    mac_vrf_vni_base: 10000
    vrfs:
      Red:
        vrf_vni: 10
        svis:
          10: 
            name: DMZ
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          20: 
            name: Internal
            enabled: true
            ip_address_virtual: 10.1.20.1/24