path: "{{lookup('env','PWD')}}"

CVP_CONFIGLETS:
 Alias_tony: "alias ship show ip interface brief"
 tonys_loopbacks: "{{ lookup('file','{{ path }}/configlets/static/tonys_loopbacks.cfg') }}"

CONTAINERS:
  DC1:
      parentContainerName: Tenant
  Spines-DC1:
      parentContainerName: DC1
  Leafs-DC1:
      parentContainerName: DC1
      configlets:
      - tonys_loopbacks

DEVICES:
  - fqdn: 'leaf1'
    parentContainerName: 'Leafs-DC1'
    configlets:
      - 'tonys_loopbacks'
  - fqdn: 'leaf2'
    parentContainerName: 'Leafs-DC1'
    configlets:
      - 'tonys_loopbacks'
  - fqdn: 'leaf3'
    parentContainerName: 'Leafs-DC1'
    configlets:
      - 'tonys_loopbacks'
  - fqdn: 'leaf4'
    parentContainerName: 'Leafs-DC1'
    configlets:
      - 'tonys_loopbacks'
  - fqdn: 'spine1'
    parentContainerName: 'Spines-DC1'
    configlets:
      - 'tonys_loopbacks'
  - fqdn: 'spine2'
    parentContainerName: 'Spines-DC1'
    configlets:
      - 'tonys_loopbacks'
  - fqdn: 'spine3'
    parentContainerName: 'Spines-DC1'
    configlets:
      - 'tonys_loopbacks'